# Generated by Django 5.1.4 on 2025-02-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exp', models.IntegerField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=1000)),
            ],
        ),
    ]
